const REMOVE_FILTER = 'REMOVE_FILTER';
const REMOVE_FILTERS = 'REMOVE_FILTERS';
const SET_COLUMN = 'SET_COLUMN';
const SET_COMPARISON = 'SET_COMPARISON';
const SET_FILTER = 'SET_FILTER';
const SET_INPUT = 'SET_INPUT';
const SET_ORDER = 'SET_ORDER';
const SET_RESULTS = 'SET_RESULTS';
const SET_SORT = 'SET_SORT';
const SET_SORT_COLUMN = 'SET_SORT_COLUMN';
const SET_VALUE = 'SET_VALUE';

export {
  REMOVE_FILTER,
  REMOVE_FILTERS,
  SET_COLUMN,
  SET_COMPARISON,
  SET_FILTER,
  SET_INPUT,
  SET_ORDER,
  SET_RESULTS,
  SET_SORT,
  SET_SORT_COLUMN,
  SET_VALUE,
};
