const SET_COLUMN = 'SET_COLUMN';
const SET_COMPARISON = 'SET_COMPARISON';
const SET_FILTER = 'SET_FILTER';
const SET_INPUT = 'SET_INPUT';
const SET_RESULTS = 'SET_RESULTS';
const SET_VALUE = 'SET_VALUE';

export {
  SET_COLUMN,
  SET_COMPARISON,
  SET_FILTER,
  SET_INPUT,
  SET_RESULTS,
  SET_VALUE,
};
